require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.3

Layout/LineLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - '*.gemspec'

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 20
